import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#e6f3fb",
        "surface-container-high": "#ddeaf2",
        primary: "#005e93",
        outline: "#707881",
        "on-surface-variant": "#404750",
        tertiary: "#7f34af",
        "surface-dim": "#cfdce4",
        "on-surface": "#111d23",
        "on-tertiary-fixed": "#2f004b",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#6a1b9a",
        error: "#ba1a1a",
        background: "#f4faff",
        "surface-container-low": "#e9f6fd",
        "inverse-surface": "#263238",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001d33",
        surface: "#f4faff",
        "tertiary-fixed": "#f4d9ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#d7e4ec",
        "primary-fixed": "#cee5ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#97cbff",
        "on-secondary-fixed": "#311300",
        "secondary-fixed": "#ffdbc8",
        "on-background": "#111d23",
        "inverse-primary": "#97cbff",
        "surface-bright": "#f4faff",
        secondary: "#984800",
        "surface-container": "#e3f0f8",
        "error-container": "#ffdad6",
        "outline-variant": "#c0c7d1",
        "tertiary-container": "#9a4fca",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1f77b4",
        "surface-tint": "#00639b",
        "surface-variant": "#d7e4ec",
        "on-secondary-fixed-variant": "#743500",
        "tertiary-fixed-dim": "#e4b5ff",
        "on-tertiary-container": "#fff5fe",
        "on-secondary-container": "#5c2900",
        "on-primary-container": "#f5f8ff",
        "on-primary-fixed-variant": "#004a76",
        "secondary-container": "#fc7d09",
        "secondary-fixed-dim": "#ffb689",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
